name: date_calendar
version: 0.2.1+1
publish_to: 'none'
description: >
  A calendar interface and Gregorian calendar implementation
homepage: https://github.com/dnfield/dart_calendar
dev_dependencies:
  test: ^1.24.9
environment:
  sdk: '>=3.1.2 <4.0.0'
